name: mini_social_app
description: A student social feed app built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
